<a href="https://colab.research.google.com/github/callejas-omar/Metodos-Numericos1/blob/main/LU%20Corregido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import scipy.linalg

def lu_solve(A, b):
    """Resuelve un sistema de ecuaciones lineales Ax = b usando la factorización LU.

    Args:
        A: Una matriz NumPy cuadrada que representa la matriz de coeficientes.
        b: Un array NumPy que representa el vector constante.

    Returns:
        Un array NumPy que representa el vector solución x.
    """
    # Obtener la factorización LU de A
    P, L, U = scipy.linalg.lu(A)

    # Imprimir las matrices P, L y U
    print("Matriz P:")
    print(P)
    print("\nMatriz L:")
    print(L)
    print("\nMatriz U:")
    print(U)

    # Resolver Ly = Pb para y usando sustitución hacia adelante
    y = scipy.linalg.solve_triangular(L, P @ b, lower=True)

    # Resolver Ux = y para x usando sustitución hacia atrás
    x = scipy.linalg.solve_triangular(U, y, lower=False)

    return x

# Ejemplo de uso
A = np.array([[1, 1, 0, 3],
              [2, 1, -1, 1],
              [3, -1, -1, 2],
              [-1, 2, 3, -1]])
b = np.array([4, 1, -3, -4])

# Calcular la solución
x = lu_solve(A, b)

# Imprimir la solución
print("\nSolución:")
for i, val in enumerate(x):
    print(f"x{i+1} = {val}")

Matriz P:
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

Matriz L:
[[ 1.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.        ]
 [ 0.66666667  1.          1.          0.        ]
 [ 0.33333333  0.8         0.6         1.        ]]

Matriz U:
[[ 3.         -1.         -1.          2.        ]
 [ 0.          1.66666667  2.66666667 -0.33333333]
 [ 0.          0.         -3.          0.        ]
 [ 0.          0.          0.          2.6       ]]

Solución:
x1 = -1.2820512820512824
x2 = 3.205128205128205
x3 = -3.6666666666666665
x4 = -0.30769230769230727
