<a href="https://colab.research.google.com/github/callejas-omar/Metodos-Numericos1/blob/main/Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libreria Numpy
##¿Para que sirve
Esta libreria se especializa en el calculo numerico y anilisis de datos, sobre todo si se trata de una gran cantidad de datos. \\
Esta libreria integra una nueva clase de objetos llamados $arrays$, los cuales permiten representar mismos tipos de datos pero en varias dimensiones, ademas de funciones donde su manipulacion es facil de hacer. \\

Una de las ventajas de esta libreria en comparacion a otras en Python es que su procesamiento con los $arays$ es mucho mas rapido que con otras, lo cual, lo hace preferible en utilizarlo en el procesamiento de vectores y matrices de unas dimensiones grandes. \\

##¿Que es un $array$?
Es una estructura de dato del mismo tipo,organizadas de diversas formas, dependiendo de las dimensiones; pueden ser desde tablas, etc.

Para acceder a los elementos contenidos en un array se usan índices al igual que para acceder a los elementos de una lista, pero indicando los índices de cada dimensión separados por comas. \\

Al igual que para listas, los índices de cada dimensión comienzan en 0.



In [3]:
import numpy as np

##Operaciones con $Arrays$
Existen dos formas de realizar operaciones matemáticas con arrays: a nivel de elemento y a nivel de array.

Las operaciones a nivel de elemento operan los elementos que ocupan la misma posición en dos arrays. Se necesitan, por tanto, dos arrays con las mismas dimensiones y el resultado es una array de la misma dimensión.

Los operadores mamemáticos $+$, $-$, $*$, $/$, $%$, $**$ se utilizan para la realizar suma, resta, producto, cociente, resto y potencia a nivel de elemento.

##Instalacion de la Libreria Numpy
El siguiente codigo sirve para instalar la libreria Numpy, en caso de no tenerlo instalado, asi que este codigo, nos servira para poder usar en totalidad la libreria.

In [4]:
# !pip install numpy

Ahora veamos ejemplos de las cosas que ya mencionamos en estos momentos...


In [6]:
#Un array Unidimensional
array_1d = np.array([1,2,3,4,5])
print("array_1d: "  ,array_1d)

#Un array Bidimensional
array_2d = np.array([[1,2,3],[4,5,6]])
print("array_2d: "  ,array_2d)

array_1d:  [1 2 3 4 5]
array_2d:  [[1 2 3]
 [4 5 6]]


Una cosa a mencionar, es que los arrays tienen propiedades utiles como: su forma ($shape$), numero de dimensiones ($ndim$), tamaño ($size$), y tipo de datos ($dtype$). \\
Ejemplo:

In [8]:
print("Forma del array", array_2d.shape)
print("Numero de dimensiones del array", array_2d.ndim)
print("Tamaño del array", array_2d.size)
print("Tipo de datos del array", array_2d.dtype)

Forma del array (2, 3)
Numero de dimensiones del array 2
Tamaño del array 6
Tipo de datos del array int64


Como mencionamos anteriormente, la libreria Numpy nos facilita con operaciones en datos de una gran dimension, en este caso, como matrices; veamos un ejemplo de multiplicacion de matrices y del calculo de la transpuesta de esta.

In [10]:
matriz_a = np.array([[1,2,3],[4,5,6]])
matriz_b = np.array([[1,2],[3,4],[5,6]])

#Multiplicacion de matrices
product = np.dot(matriz_a,matriz_b)
print("Multiplicacion de matrices: \n", product)

#Transpuesta de una matriz
print("Transpuesta de la matriz A: \n", np.transpose(matriz_a))

#Transpuesta de una matriz
print("Transpuesta de la matriz B: \n", np.transpose(matriz_b))

Multiplicacion de matrices: 
 [[22 28]
 [49 64]]
Transpuesta de la matriz A: 
 [[1 4]
 [2 5]
 [3 6]]
Transpuesta de la matriz B: 
 [[1 3 5]
 [2 4 6]]


Y asi podemos usar la libreria Numpy, pero por el moemnto estas son las cosas basicas que podemos hacer con ellas.